### ISSUE TITLE
Mi A2 support?

### ISSUE THREAD

**Issue by KokaKiwi** [DerpLab/Updater-Stuff#9]
As of the last official build, DerpFest seems to use this repo for update information with OpenDelta, but actually fails to check latest version as there's actually no JSON data for `jasmine_sprout` platform.
Is it planned to add it later, or for a future release?

**Comment by idoybh** [comment]
Depends on the maintainer of the device. If he decides to use OpenDelta he will push the new version here. The first version must be a manually flashed file anyways. So this question is asked way too early. And is irrelevant

**Comment by KokaKiwi** [comment]
> Depends on the maintainer of the device. If he decides to use OpenDelta he will push the new version here.

Well kinda supposed so, just wondered as it was labelled as "Official" i thought things about the device was planned to come here but okay.

> The first version must be a manually flashed file anyways. So this question is asked way too early.

Yeah, just asked to know about how things were planned to be handled (if there were such things ofc)

> And is irrelevant

uh okay, kinda wondering how as it's related to this ROM, this repository and the whole updater stuff. As said earlier, just asked to know about potential plan about this repo.
But well OK, won't ask again i guess :woman_shrugging:

**Comment by idoybh** [comment]
I get you now. This repo surely needs a readme as well.
